[package]
name = "biostats"
version = "0.1.0"
authors = ["Aaron Zorel"]
edition = "2018"
license = "Apache-2.0"
description = "A bioinformatics library"
repository = "https://github.com/Rustinante/biostats"

[dependencies]
ndarray = {version = "0.12.1"}
rayon = "1.1.0"
num = "0.2"
analytic = "0.6.0"

[dev-dependencies]
tempfile = "3.0.8"
ndarray-rand = "0.9.0"
rand = "0.6.5"
